In [1]:
import numpy as np

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [5]:
np.arange(10,50,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [6]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
np.random.rand(1)

array([0.45046828])

In [9]:
np.random.rand(25)

array([3.96393404e-01, 8.23242357e-01, 6.15210611e-01, 3.31795568e-01,
       8.61235665e-01, 4.09204185e-01, 8.07350790e-01, 9.01770408e-01,
       1.82385712e-01, 7.58294509e-01, 6.65633797e-01, 7.93136712e-01,
       9.10186342e-01, 8.08641698e-01, 5.51132660e-01, 5.61952270e-04,
       8.65369447e-01, 9.16474432e-01, 5.50272819e-01, 9.20356728e-01,
       9.56005997e-01, 5.96975128e-01, 9.44384267e-01, 9.72351888e-01,
       9.15880952e-01])

In [10]:
np.linspace(0.01,1,10)

array([0.01, 0.12, 0.23, 0.34, 0.45, 0.56, 0.67, 0.78, 0.89, 1.  ])

In [11]:
ar = np.arange(1,26).reshape(5,5)
ar

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [12]:
ar=np.arange(0,9).reshape(3,3)
ar

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
ar[1:3]

array([[3, 4, 5],
       [6, 7, 8]])

In [14]:
ar = np.arange(1,26).reshape(5,5)
ar[0:2,0:2]

array([[1, 2],
       [6, 7]])

In [15]:
ar=np.arange(1,26).reshape(5,5)
ar

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [16]:
ar[1:]

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [17]:
ar[2:5,1:4]

array([[12, 13, 14],
       [17, 18, 19],
       [22, 23, 24]])

In [18]:
mat=np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [19]:
mat[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [20]:
mat[4:]


array([[21, 22, 23, 24, 25]])

In [21]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [22]:
np.sum(mat)

325

In [23]:
np.sum(mat,axis=1)

array([ 15,  40,  65,  90, 115])

In [24]:
arr=np.arange(0,12).reshape(3,2,2)
arr

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [25]:
type(arr)

numpy.ndarray

In [26]:
arr.dtype

dtype('int32')

In [27]:
v=np.random.randint(1,100,20).reshape(4,5)
v

array([[66, 98, 22, 18, 69],
       [39, 67, 12, 82, 41],
       [70,  6, 38, 32, 73],
       [82, 41, 58, 80, 53]])

In [28]:
asc=np.sort(v)
asc

array([[18, 22, 66, 69, 98],
       [12, 39, 41, 67, 82],
       [ 6, 32, 38, 70, 73],
       [41, 53, 58, 80, 82]])

In [29]:
#asending order
np.flip(v)

array([[53, 80, 58, 41, 82],
       [73, 32, 38,  6, 70],
       [41, 82, 12, 67, 39],
       [69, 18, 22, 98, 66]])

In [30]:
np.copy(v)

array([[66, 98, 22, 18, 69],
       [39, 67, 12, 82, 41],
       [70,  6, 38, 32, 73],
       [82, 41, 58, 80, 53]])

In [31]:
np.flip(asc)

array([[82, 80, 58, 53, 41],
       [73, 70, 38, 32,  6],
       [82, 67, 41, 39, 12],
       [98, 69, 66, 22, 18]])

In [32]:
np.copy(v)

array([[66, 98, 22, 18, 69],
       [39, 67, 12, 82, 41],
       [70,  6, 38, 32, 73],
       [82, 41, 58, 80, 53]])

In [33]:
vcopy=np.copy(v)
vcopy

array([[66, 98, 22, 18, 69],
       [39, 67, 12, 82, 41],
       [70,  6, 38, 32, 73],
       [82, 41, 58, 80, 53]])

In [34]:
vcopy [:5] = 99
vcopy

array([[99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99]])

In [35]:
v


array([[66, 98, 22, 18, 69],
       [39, 67, 12, 82, 41],
       [70,  6, 38, 32, 73],
       [82, 41, 58, 80, 53]])

In [36]:
iden = np.eye(5)
iden

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [37]:
iden.flatten()

array([1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 1.])

In [38]:
mat =  np.arange(9).reshape(3,3)
mat

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [39]:
np.append(mat,[[9,10,11]],axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [40]:
np.append(mat,[[9,10,11]],axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [41]:
np.hsplit(mat,3)

[array([[0],
        [3],
        [6]]),
 array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]])]

In [42]:
np.hstack((mat,[[12],[13],[14]]))

array([[ 0,  1,  2, 12],
       [ 3,  4,  5, 13],
       [ 6,  7,  8, 14]])

In [43]:

np.eye(4)+6

array([[7., 6., 6., 6.],
       [6., 7., 6., 6.],
       [6., 6., 7., 6.],
       [6., 6., 6., 7.]])

In [44]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [45]:
#genrate floting values
rarr=np.random.uniform(0,15,10)
rarr

array([ 9.0618113 ,  5.25267501,  4.58098163, 13.67388676, 11.3399713 ,
        5.11057398,  1.71945576, 12.678817  , 10.05198683,  8.19948792])

In [46]:
np.ceil(rarr)

array([10.,  6.,  5., 14., 12.,  6.,  2., 13., 11.,  9.])

In [47]:
np.round(rarr,decimals=2)

array([ 9.06,  5.25,  4.58, 13.67, 11.34,  5.11,  1.72, 12.68, 10.05,
        8.2 ])

In [48]:
np.floor(rarr)

array([ 9.,  5.,  4., 13., 11.,  5.,  1., 12., 10.,  8.])

In [50]:
v=np.arange(0,25).reshape(5,5)
v

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [51]:
np.sum(v)

300

In [52]:
np.sum(v,axis=0)

array([50, 55, 60, 65, 70])

In [53]:
np.min(v,axis=0)

array([0, 1, 2, 3, 4])

In [54]:
    np.max(v,axis=0)

array([20, 21, 22, 23, 24])

In [55]:
np.var(v,axis=0)

array([50., 50., 50., 50., 50.])

In [56]:
np.std(v,axis=0)

array([7.07106781, 7.07106781, 7.07106781, 7.07106781, 7.07106781])

In [57]:
nv=np.full(10,'NaN')
nv

array(['NaN', 'NaN', 'NaN', 'NaN', 'NaN', 'NaN', 'NaN', 'NaN', 'NaN',
       'NaN'], dtype='<U3')

In [58]:
nv[5]=200
nv

array(['NaN', 'NaN', 'NaN', 'NaN', 'NaN', '200', 'NaN', 'NaN', 'NaN',
       'NaN'], dtype='<U3')

In [59]:
np.nonzero([1,0,2,0,0,4,0,8])

(array([0, 2, 5, 7], dtype=int64),)

In [60]:
vr=np.arange(100,151)
vr

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150])

In [61]:
np.flip(vr)


array([150, 149, 148, 147, 146, 145, 144, 143, 142, 141, 140, 139, 138,
       137, 136, 135, 134, 133, 132, 131, 130, 129, 128, 127, 126, 125,
       124, 123, 122, 121, 120, 119, 118, 117, 116, 115, 114, 113, 112,
       111, 110, 109, 108, 107, 106, 105, 104, 103, 102, 101, 100])

In [62]:
np.flip(vr)


array([150, 149, 148, 147, 146, 145, 144, 143, 142, 141, 140, 139, 138,
       137, 136, 135, 134, 133, 132, 131, 130, 129, 128, 127, 126, 125,
       124, 123, 122, 121, 120, 119, 118, 117, 116, 115, 114, 113, 112,
       111, 110, 109, 108, 107, 106, 105, 104, 103, 102, 101, 100])

In [63]:
np.flip(vr)



array([150, 149, 148, 147, 146, 145, 144, 143, 142, 141, 140, 139, 138,
       137, 136, 135, 134, 133, 132, 131, 130, 129, 128, 127, 126, 125,
       124, 123, 122, 121, 120, 119, 118, 117, 116, 115, 114, 113, 112,
       111, 110, 109, 108, 107, 106, 105, 104, 103, 102, 101, 100])

In [64]:
vr=np.ones(64).reshape(8,8)
vr

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [65]:
vr[::2,::2]=1
vr[1::2,1::2]=0
vr

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])